#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This file must be called with sudo privileges"
	exit 1
fi

chown root:root logging args2array backUP install
chmod 755 logging args2array backUP
mkdir -p /usr/local/lib/backUP /usr/local/etc/backUP
ln -f backUP /usr/local/bin
ln -f args2array /usr/local/lib/backUP
ln -f logging /usr/local/lib/backUP

touch /usr/local/etc/backUP/backUP.conf /usr/local/etc/backUP/backup.txt
chmod 660 /usr/local/etc/backUP/backUP.conf /usr/local/etc/backUP/backup.txt
chown root:root /usr/local/etc/backUP/backUP.conf /usr/local/etc/backUP/backup.txt
